### ISSUE TITLE
Pellmon mqtt issue 

### ISSUE THREAD

**Issue by lindberg87** [motoz/pellmonMQTT#2]
Hey.

I got this error then I try to start pellmon mqtt script.

Traceback (most recent call last):
  File "pellmonMQTT.py", line 25, in <module>
    import paho.mqtt.client as mosquitto
ImportError: No module named paho.mqtt.client

I have change python to default to run python 3 and the paho mqtt should be installed.

Do anyone have a suggestion what to do about it ? 

Best Regards.

**Comment by motoz** [comment]
Neither PellMon nor pellmonMQTT runs on python 3, i.e. if the command 'python' starts python 3 instead of python 2 then it doesn't work.

**Comment by lindberg87** [comment]
I got it to work. I change python back to python 2 and installed paho mqtt now it runs and it contacts my mqtt broker Home assistant :D

**Comment by motoz** [comment]
Great!
